version: "3.7"
services:
  db:
    # 컨테이너 이름 지정
    container_name: db
    # 이미지 지정 - Official Images로 컨테이너를 생성
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: text_board
      MYSQL_USER: messi
      MYSQL_PASSWORD: messi
      MYSQL_ROOT_PASSWORD: root
    # 호스트에 있는 폴더를 컨테이너 안에 있는 폴더로 마운트
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d
    #   - ./mysql/data:/var/lib/mysql:rw
    # 연결 포트 지정
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
  app:
    container_name: php
    image: php:fpm
    # db 컨테이너가 올라간 후 app 컨테이너를 올린다.
    depends_on:
      - db
    ports:
      - "9000:9000"
    volumes:
      - ./nginx/html:/var/www/html
    environment:
      PMA_HOST: db
      PMA_USERE: dico
      PMA_PASSWORD: root
    command: bash -c "docker-php-ext-install mysqli && php-fpm"
  web:
    container_name: nginx
    # 이미지 지정 - 직접 작성한 dockerfile을 실행하여 컨테이너 생성
    build:
      context: ./nginx
      dockerfile: dockerfile
    depends_on:
      - app
    volumes:
      - ./nginx/html:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    links:
      - app
    restart: always
